### ISSUE TITLE
The GLFW project won't build

### ISSUE THREAD

**Issue by jeffsaremi** [PacktPublishing/Learn-OpenGL#1]
If you paste the main.cpp from chapter 2 into the solution file from chapter 1 you'll get a ton of `unresolved external symbol __glew* errors`
For instance try opening this project:
`Learn-OpenGL\Chapter01\GLFW\Windows\Relative Linking`
and then pasting any of the files from here:
`Learn-OpenGL\Chapter02\Shaders`
or sibling folders.

Example compilation errors:
```
1>------ Build started: Project: GLApp, Configuration: Debug Win32 ------
1>main.cpp
1>LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library
1>main.obj : error LNK2001: unresolved external symbol ___glewBindBuffer
1>main.obj : error LNK2001: unresolved external symbol ___glewBufferData
1>main.obj : error LNK2001: unresolved external symbol ___glewDeleteBuffers
1>main.obj : error LNK2001: unresolved external symbol ___glewGenBuffers
1>main.obj : error LNK2001: unresolved external symbol ___glewAttachShader
...

```

**Comment by techsachinkumar** [comment]
Hi @jeffsaremi 

Did you link all of the libraries which are required?
As I can see from the error log, its showing errors related to glew for which the libraries are not defined within the VS project folder for chapter 2 it seems.

Could you try using the libraries following chapter 1 samples and get it to run ?
Also could you brief up in detail regarding the same.

Regards,

**Comment by jeffsaremi** [comment]
It was related to the #define GLEW_STATIC
