### ISSUE TITLE
Chapter03

### ISSUE THREAD

**Issue by FusionOpz** [PacktPublishing/Learn-OpenGL#2]
Theres a bug that I can't track down regarding Chapter03, at least on macOS 10.14.3, after updating the vertex shaders to what's in the book and in this repo I do not get any spinning mario.  Haven't tried on windows... yet

**Comment by FusionOpz** [comment]
I've also managed to reproduce this issue in VS2019 on Windows 10 1903 with the latest GLFW, GLEW, GLM and SOIL2

**Comment by dbampersand** [comment]
Seems to be that transform is uninitialized, I fixed this by changing the line,

`glm::mat4 transform;`

to 

`glm::mat4 transform = glm::mat4(1.0f);`

**Comment by FusionOpz** [comment]
I don’t see that line anywhere in the chapter03 code...

**Comment by dbampersand** [comment]
It's on line 150 of https://github.com/PacktPublishing/Learn-OpenGL/blob/master/Chapter03/Transformations/main.cpp

The reason for this is either compiler differences or library updates have broken it, or possible it was just a typo, so you'll have to change that line. 

e: having looked into this a bit more, seems to be a change in glm 0.9.9; previously it instantiated automatically to identity (that is to say, 1).

**Comment by FusionOpz** [comment]
ah, I see it now, this is why I shouldn't look at code on my phone >.<

**Comment by James-Elliman** [comment]
This also applies for the other Mat4 objects i.e.:

glm::mat4 projection = glm::mat4(1.0f);
...
glm::mat4 model = glm::mat4(1.0f);
glm::mat4 view = glm::mat4(1.0f);
